<a href="https://colab.research.google.com/github/NeoBro34/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.array([1, 2, 5, 7])
print('numpy_array', arr)

arr.shape

numpy_array [1 2 5 7]


(4,)

In [5]:
arr2 = np.array([[1, 2, 5, 7], [1, 4, 6, 7]])
print('numpy_array2', arr2)

arr2.shape

numpy_array2 [[1 2 5 7]
 [1 4 6 7]]


(2, 4)

In [6]:
# dtype()
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [8]:
# reshape()
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape((2, 3))
print('shaped_array', b)

shaped_array [[1 2 3]
 [4 5 6]]


In [9]:
# astype()
a = np.array([1, 2, 3])
b = a.astype(float)
print('flat:', b)

flat: [1. 2. 3.]


In [10]:
# np.zeros(),  np.ones() => dummy data
z = np.zeros((2, 3))
o = np.ones((2, 3))

print('zeros:', z)
print('ones:', o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# ndim
a = np.array([[1, 2], [3, 4]])
print('ndim', a.ndim)

ndim 2


In [12]:
# arange()
a = np.arange(1,7)
print('arange:', a)

arange: [1 2 3 4 5 6]


In [14]:
# sum(), mean(), max(), min()

a = np.array([1, 2, 3, 4])
print('sum:', a.sum())
print('mean:', a.mean())
print('max:', a.max())
print('min:', a.min())

sum: 10
mean: 2.5
max: 4
min: 1


In [15]:
# flatten()  2D arrayni => 1D arrayga

a = np.array([[1, 2], [3, 4]])
print('flatten:', a.flatten())

flatten: [1 2 3 4]


In [17]:
# T (Transpose) 2arrayning birxil indexdagilarni addelni arrayga birlashtirib beradi
a = np.array([[1, 2, 5], [3, 4, 7]])
print('transpose:', a.T)

transpose: [[1 3]
 [2 4]
 [5 7]]


In [18]:
# dot() @
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print('dot/multiplication:', a.dot(b))

dot/multiplication: [[ 4  4]
 [10  8]]


In [21]:
# random.rand()
a = np.random.rand(2, 3) # => 0.0 ~ 1.0  / 0.0 included / 1.0 excluded
print('random rand:', a)

random rand: [[0.69682778 0.58525311 0.71796997]
 [0.00606783 0.7019261  0.29876788]]
